### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by Fredehagelund92** [herkyl/ingredients-parser#1]
Which files do i need to edit to change the language?

**Comment by herkyl** [comment]
You would have to fork the project and edit the [`rules.pegjs`](https://github.com/herkyl/ingredients-parser/blob/master/rules.pegjs) file. I don't think there is a good way of doing it as a part of this project since not only are all words different but also the rules of how to bind them.

**Comment by Fredehagelund92** [comment]
Okay, but what about all this in the spec folder. I guess this is test data, am i suppose to change this? 

Beside that if a string looked like this "1 x 500g flour" it seem not to be able to remove that x?

**Comment by herkyl** [comment]
You would have to change the specs as well.
Currently the `x` in `1 x 500g flour` doesn't get parsed but a rule could be made to omit this from the parsed result.

**Comment by herkyl** [comment]
Closing this for now, feel free to ask more questions though.
