### ISSUE TITLE
unit should be singular

### ISSUE THREAD

**Issue by abate** [herkyl/ingredients-parser#2]
Hello,
I've noticed that when parsing a phrase like "3 cups flour" the unit I get is cups and not cup (plural vs singular).
I think, for consistency, the unit should always be singular. I'm not quite sure how to change the parser
in an easy way to take this into account. My problem is that when using 'ingredient-parser' with
the npm package 'convert-unit', the latter accepts only units as singular, therefore I get an error for cupS.

**Comment by herkyl** [comment]
I see why this would be an issue for you. However ingredients-parser only focuses on finding which part of the given string is a unit, amount or ingredient.
If you wish to normalise units I recommend you to create a separate layer for normalising various unit namings into one singular unit name.
