### ISSUE TITLE
parsing preparations techniques

### ISSUE THREAD

**Issue by abate** [herkyl/ingredients-parser#4]
I'm using the usda db and portions are classified w.r.t. possible way to describe/prepare an ingredient.

For example "3 cups of chicken breast chopped or diced" . The idea would be to recognize the "chopped or diced" part.

this is an incomplete list of possible preparations and imprecise units you can find in the database.
For the moment I'm using this two list with regexps on the ingredient name to guess and refine
the parsing of my ingredients.

I think this would be a nice addition to this library. Not quite sure if this should be an extension of the
grammar, or a stand alone heuristic to be run on the ingredient name part once the parsing is done. Maybe all the imprecise units can be added to the grammar, but I'd like to know your advice before preparing a PR.

```
preparations = [
  "cubed", "chopped", "diced", "cooked", "strips", "crushed", "rinsed",
  "drained", "grated", "halves", "pieces", "whole", "large", "medium", "small",
  "pureed", "quartered", "shelled", "shredded", "sifted", "slivered", "spooned",
  "stirred", "thawed", "undrained", "unpacked", "unprepared", "unsifted",
  "unthawed", "whipped", "pitted", "frozen", "unpeeled", "peeled", "fillet",
  "assorted", "boneless", "rounded", "brownulated"
]

unprecise_units = [
  "bag", "bar", "bottle", "bowl", "breast", "bulb", "bun", "bunch", "can",
  "carton", "cone", "clove", "container", "large", "medium", "mini", "small",
  "cube", "fillet", "head", "unit", "jar", "pack", "package", "packet", "patty",
  "piece", "portion", "servings", "roll", "slice"
]
```

**Comment by herkyl** [comment]
Looks good @abate!

I recommend you to make two separate commits:

## First Commit

Add `unprecise_units` to the ruleset.

For an example see how "few" and "couple" are defined:

Adding them to the `amount` group.
https://github.com/herkyl/ingredients-parser/blob/master/rules.pegjs#L28-L29

Defining `couple`
https://github.com/herkyl/ingredients-parser/blob/master/rules.pegjs#L87-L88

## Second Commit

Parse out possible `preparations`.

You need to add it as an option to https://github.com/herkyl/ingredients-parser/blob/master/rules.pegjs#L5
After that you have to define them as a rule.

There are multiple ways to use them in a sentence, watch out for that:
One cup of chopped onions
One cup of onions, chopped

## Lastly
If you need any help feel free to ask.

**Comment by abate** [comment]
I'm working on it (bit busy this week). i'll send you a PR soon.

**Comment by abate** [comment]
I've prepared this pull request #5 and I think I've introduced a small bug in the process, but I'm not quite able to understand what I'm doing wrong.

I've scripted the generation for all the imprecises rules. some how the makefile can't find npm, but it works calling manually  `npm run-script --silent units > unprecise.pegjs ` 

you can get the entire patch, or just the unprecise.pegjs file and discard the rest .

I've also added cl and dl (centiliters and deciliters) 

I think there is a bit more work to do. let me know how you want to proceed.

**Comment by herkyl** [comment]
Looks good! Merging it.

There are some stuff that could be improved on though:
```js
parse('two bowls of large potatoes');
/*
{ amount: 'two',
  ingredient: 'bowls of large potatoes',
  unit: 'large' }
*/
```
